// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyqLQ0ZyBI-vIkGt3gem4H2a88LVO6ul8',
    appId: '1:763712242192:web:e48df466cf58b37dc00095',
    messagingSenderId: '763712242192',
    projectId: 'chat-app-6b681',
    authDomain: 'chat-app-6b681.firebaseapp.com',
    storageBucket: 'chat-app-6b681.appspot.com',
    measurementId: 'G-WMK49CN31K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg0gFznhsx1Gan37hdZfO9giQWmpxgWhk',
    appId: '1:763712242192:android:b3fcdceb9c0301edc00095',
    messagingSenderId: '763712242192',
    projectId: 'chat-app-6b681',
    storageBucket: 'chat-app-6b681.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1z6_Jg0I_nG6oRCEwaG7tI8KDTw9YBgI',
    appId: '1:763712242192:ios:51a81fb0f1b8d49fc00095',
    messagingSenderId: '763712242192',
    projectId: 'chat-app-6b681',
    storageBucket: 'chat-app-6b681.appspot.com',
    iosClientId: '763712242192-m0rfs9e7i3eugsso4igfv4iupn2sfqgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1z6_Jg0I_nG6oRCEwaG7tI8KDTw9YBgI',
    appId: '1:763712242192:ios:fdcce1bf9a9f0deac00095',
    messagingSenderId: '763712242192',
    projectId: 'chat-app-6b681',
    storageBucket: 'chat-app-6b681.appspot.com',
    iosClientId: '763712242192-r9ip8jri5earmh6nm7lhrc3e6nt3kq5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
